"""Add a synthetic bookkeeping run to a disposable demo database.

Run after ``seed_demo_crm.py`` with the same ``SHIMLINE_DEMO_DB``. The company
is generated by ``shimline.synthetic_books`` with seeded accounting defects, so
the review screen shows real findings, proposals and reconciliation output
without any real client data.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import app
from shimline import work_engine
from shimline.synthetic_books import generate_company


def main() -> int:
    target = os.environ.get("SHIMLINE_DEMO_DB", "").strip()
    if not target:
        raise SystemExit("SHIMLINE_DEMO_DB is required")
    app.DB_PATH = Path(target).resolve()
    conn = app._db()
    row = conn.execute(
        "SELECT e.id, e.organization_id FROM engagements e ORDER BY e.created_at LIMIT 1").fetchone()
    if not row:
        raise SystemExit("Seed the demo CRM first")
    company = generate_company(int(os.environ.get("SHIMLINE_DEMO_SEED", "3")))
    analysis = work_engine.analyze(company.objects, company.evidence)
    run_id = work_engine.persist_analysis(
        conn, organization_id=row[1], engagement_id=row[0], connection_id=None,
        analysis=analysis, evidence=company.evidence, provider="synthetic")
    print(f"{run_id}: {len(analysis.findings)} findings, {len(analysis.proposals)} proposals")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
